### ISSUE TITLE
SuiteCloud Extension for VSCode - Compare to Account File doesn't work as expected

### ISSUE THREAD

**Issue by Elroban85** [oracle/netsuite-suitecloud-sdk#841] opened 2024-08-26 11:09 UTC
### Select the SuiteCloud tool where you encountered the issue

SuiteCloud Extension for VSCode

### Version of the SuiteCloud Tool

2.0.0

### Operating system

Windows 11 23H2

### Node Version / VSCode Version

v18.20.3

### JAVA Version

java 17.0.5+9-LTS-191

### Bug description

Months ago this function was working as expected but since quite some time it seems to be broken.
Whenever you try to compare a file to the account, only the first comparison is working like it should. All others will be compared against the first selected local file until you reload VS Code.

### Steps To Reproduce

1. You select a file in the cabinet and choose 'Compare to Account File'
2. You get a diff view comparing the account and local file, so far so good
3. You select a new file in the cabinet and choose 'Compare to Account File'
4. Incorrect diff view pops up comparing account file to the file from step 1.

**Comment by davidecorreu** [comment] 2024-08-27 16:58
Hi @Elroban85,

I'm not able to reproduce your described behavior. I have tried in 2 machines, one with macos and another one with Windows.

These are the specification on my windows machine. I just see a different java version, and I don't know which is your vscode version.

**Select the SuiteCloud tool where you encountered the issue**
SuiteCloud Extension for VSCode

**Version of the SuiteCloud Tool**
2.0.0

**Operating system**
Windows 11 pro 23H2

**Node Version / VSCode Version**
This should be the vscode version, in my case: 1.92.2
(internally uses nodejs 20.14.0)

**JAVA Version**
"17.0.12" 2024-07-16 LTS


Please try to update your java version to the latest oracle available for java 17 LTS, and also update your vscode version to the latest.

If the problem persists, I would like to know even more preciselly, if you have more files open, if you close the comparation opened tabs between first and second comparision, and how do you trigger the compare files commands (I might be missing something that you are doing differntly).

**Comment by Elroban85** [comment] 2024-08-27 18:59
Hi @davidecorreu 

My VS Code version is 1.92.2, and I have just updated my JDK to Java 17.0.12 (2024-07-16 LTS), so everything should be up to date.

It doesn't matter if I have multiple files open or not; the file to be compared seems to be cached for a while. I noticed that if I leave VS Code idle for some time (not sure exactly how long), it will eventually compare the latest selection.
**I was mistaken—it is not the local file that is cached, but rather the account file as you can see in the video. Everything is compared to file 2.**

In the attached video, you can see what I do and how I perform the comparison.

https://github.com/user-attachments/assets/1b506bcf-79a4-47ed-8ff1-88c4502a04fb

**Comment by davidecorreu** [comment] 2024-08-29 13:00
Hi @Elroban85 ,

Thanks for the provided video, it actually helped in the investigation.

I have been able to reproduce the behavior by comparing files in a project that has git vcs initialized on it.
So far I tried with 3 files that haven't been committed, and have the same green color as in your video.
I'm not sure why this is happening but at least we can replicate for further investigation. 

This it's just a quick heads up message, to let you know that we are able to reproduce the same behavior.

**Comment by davidecorreu** [comment] 2024-08-30 15:54
Hi @Elroban85 ,

The problem it's not related with git. After some digging I have found that our vscode-extension implementation code doesn't work well when trying to compare multiple files.

The work around is to close any previous comparison tab generated by the **Compare with Account File** command on vscode before trying to compare a new file. If you do so, you'll see that account file content will be properly refreshed in the new comparison tab.

I now this isn't very convenient and will need to decide how to tackle this. We'll let you know about it soon.

**Comment by Elroban85** [comment] 2024-08-30 15:57
Not at my pc at the moment but you're sure that works?
In my video I closed all file tabs and it didn't work though, or do you mean in a different way?

**Comment by davidecorreu** [comment] 2024-08-30 16:09
I'll investigate further, but you are right, you are closing al the tabs in you video.
I did close the tab manually by clicking on the X, which who knows if it makes a difference.
Anyway I have seen that we are reusing always a vscode text document provider with the same scheme label, and I suspect that could be the source of the problem.

We'll keep investigating further.

**Comment by kostiato** [comment] 2024-08-31 09:07
I was experiencing the same issue long time ago with version 1.6.0.
I found that it happened only with installed and activated GitHub and/or GitHub Pull Requests VSCode extensions. Uninstalled them and Compare to Account File started working again.

**Comment by davidecorreu** [comment] 2024-09-16 13:47
Hi @Elroban85 ,

We have just released SuiteCloud Extension for VSCode version 2.0.1.
**Compare to Account File** should work as expected now.

**Closed by davidecorreu** 2024-09-16 13:47 UTC
Labels: bug, tracked
