### ISSUE TITLE
Deploy timeout 

### ISSUE THREAD

**Issue by manueltoniato** [oracle/netsuite-suitecloud-sdk#590] opened 2022-07-05 16:41 UTC
### Your environment
**OS** : Windows 10
**Node.js version** : v16.14.0
**suitecloud-cli version** : 1.4.0 (why is it different from the version exposed by npm, i.e. 1.5.0)?
**Terminal/CMD tool** :  Ubuntu WSL

### Describe the bug
Even for small number of objects (forms, fields, templates), i.e. 40, the deploy operation takes more than 10 minutes and stops for timeout reasons. This is the content list of one of my simpler projects. As you can see it contains just 9 custom fields, 3 custom records, a few scripts and a few custom forms. Nevertheless the deploy cannot be carried out successfully. Take into account that if I restrict the number of files deployed by listing them one by one in deploy.xml everything works like a charm. The same happens if I remove some files (for example removing the forms).

cseg_mtr_event.xml
custbody_mtr_linked_journal_entry.xml
custbody_mtr_parent_transaction.xml
custbody_mtr_payment_split_completed.xml
custbody_mtr_payment_summary.xml
custcol_mtr_membership_end_date.xml
custcol_mtr_membership_start_date.xml
custcol_mtr_original_gross_amount.xml
custentity_mtr_eleinv_praddrcode.xml
custentity_mtr_pec.xml
custform_mtr_ff_std_cash_refund.xml
custform_mtr_ff_std_cash_sale.xml
custform_mtr_ff_std_credit_memo.xml
custform_mtr_ff_std_customer_payment.xml
custform_mtr_ff_std_customer_refund.xml
custform_mtr_ff_std_employee.xml
custform_mtr_ff_std_inventory.xml
custform_mtr_ff_std_invoice.xml
custform_mtr_ff_std_non_inventory.xml
custform_mtr_ff_std_purchase_order.xml
custform_mtr_ff_std_return_authorization.xml
custform_mtr_ff_std_return_authorization_cm.xml
custform_mtr_ff_std_return_authorization_cr.xml
custform_mtr_ff_std_sales_order.xml
custform_mtr_ff_std_sales_order_cs.xml
custform_mtr_ff_std_sales_order_inv.xml
custform_mtr_ff_std_vendor_bill.xml
custform_mtr_ff_std_vendor_credit.xml
custitem_mtr_event_end_date.xml
custitem_mtr_event_start_date.xml
customlist_mtr_event_status.xml
customlist_mtr_payment_fee.xml
customrecord_cseg_mtr_event.xml
customrecord_mtr_configuration.xml
customrecord_mtr_payment_split.xml
customrole_mtr_ff_em_controller.xml
customrole_mtr_tba.xml
customscript_aly_create_payment_je_ue.xml
customscript_aly_custom_obj_import_sched.xml
customscript_aly_custom_obj_import_suite.xml
customscript_aly_custom_obj_import_tab.xml

Thanks in advance for your help.

**Comment by tourajvaziri** [comment] 2022-07-07 13:41
Hello!
It's possible to timeout even with smaller projects since although there's only 40 objects mentioned by the client, custom form and custom record are heavy objects.  For example, one custom record can have many custom fields inside and up to 1000 instance entries.  If you consider the time and operation for each instance entry alone, it would take some time.  Although it times out on the devtools side, kindly ask customer to check the stacktrace in their account.  If customer go to Customization > Suitecloud Development > Deployment Audit Trail, the deployment trail will be listed there once it finishes (either successful or failed deployment).

**Comment by alii-gator** [comment] 2022-09-27 12:07
@manueltoniato Are you still facing this issue?

**Comment by bretislav** [comment] 2023-03-17 00:44
this is still an issue for our company

**Comment by alii-gator** [comment] 2023-03-17 18:05
@bretislav Are you behind any proxy network?

**Comment by jpdevrzmz** [comment] 2023-12-09 02:06
hi @tourajvaziri - my team is getting the same error as @manueltoniato. Mainly for Sandboxes. Is there a final solution for this? NS is pushing so hard to use the Suitecloud Development Framework and follow good Continuous Deployment, but this kind of error is a business stopper.

**Comment by alii-gator** [comment] 2023-12-12 14:16
@jpdevrzmz are you behind any proxy? or do you have a normal internet connection?

**Comment by hscott-cfgms** [comment] 2023-12-13 18:26
I am seeing the same issue. I am behind a normal internet connection.

**Comment by jpdevrzmz** [comment] 2023-12-13 20:12
Hi all- after several debugging sessions we found out it was caused by custom segments checks, even if we do not deploy the segment instances. We ended up moving many things to the manifest.xml as dependencies to have a lighter deployment. Not ideal but it was the only thing we could do.

**Comment by lfpvillegas** [comment] 2024-02-13 15:59
Hi @jpdevrzmz . Thanks for telling us the workaround. 
I am going to close this issue since it's related to the checks that are performed server side. In this repository we only track the issues directly related to the CLI and extensions.
However, please create an issue via customer support for further investigation.

Thanks

**Closed by lfpvillegas** 2024-02-13 15:59 UTC
Labels: bug
