### ISSUE TITLE
As soon as you fire suitecloud project:deployDisplay the Account Name or Account ID to which the SDF CLI is abou

### ISSUE THREAD

**Issue by naren2k6** [oracle/netsuite-suitecloud-sdk#161] opened 2020-07-10 10:32 UTC
### Your environment
**OS** : e.g. iOS Mohave 10.14.6 /Windows 10/Ubuntu 16.04
**Node.js version** : e.g. 12.14.1
**suitecloud-cli version** : Run `suitecloud --version` to check the version
**Terminal/CMD tool** : e.g. PowerShell/WebStormTerminal/VSCodeTerminal/iTerm

### To Reproduce
1. Run suitecloud {command} -i

**Comment by alii-gator** [comment] 2020-07-10 10:51
@naren2k6 it the duplicate of #162?

**Closed** 2020-07-10 11:17 UTC
Labels: bug
