### ISSUE TITLE
As soon as you fire "suitecloud project:deploy" , kindly display the "Account Name" or "Account ID" of the NetSuite account to which the CLI is about to deploy

### ISSUE THREAD

**Issue by naren2k6** [oracle/netsuite-suitecloud-sdk#162] opened 2020-07-10 10:36 UTC
![image](https://user-images.githubusercontent.com/11972740/87145417-e59ff500-c2c6-11ea-9ad5-cf8d34826ed5.png)

Look at the picture above , 
It would be good if the Account Name or Account ID is included in the text "Deploying ....."

This is needed because its makes it easier for the  developer who may is working parallely  on multiple accounts , without having to do "account:setup" everytime  to check which is the active account

**Comment by alii-gator** [comment] 2020-07-10 10:50
@naren2k6 sure, we have discussed it internally. Sounds reasonable. Will bring this up with the team. Thanks

**Comment by alii-gator** [comment] 2020-07-13 08:17
This is a duplicate of #20 
The suggestion is already under consideration so i will close this issue as we already have issue for this.

**Closed by alii-gator** 2020-07-13 08:17 UTC
Labels: bug
